### ISSUE TITLE
editor focuses itself on creation

### ISSUE THREAD

**Issue by nightwing** [MikeRatcliffe/Acebug#3]
calling new editor focuses itself even if window isn't focused
and since our window contains only one focusable element calling editor.blur()  doesn't help

should we ask Fabian to change this, or try to find a workaround?
i think calling focus in constructor is wrong anyway.

**Comment by MikeRatcliffe** [comment]
Our version is from back in November some time or maybe earlier so there is no point reporting issues to Fabian. Ideally we would get the latest version working though. I have been unable to get more recent versions to start up ... I guess because of incompatible plugins. The version that we had working earlier turned out to be your version ... I must have downloaded your forked version by accident :o/

I guess if we copied the configuration from this version then it might work (same plugins etc).

**Comment by nightwing** [comment]
in devel i am using the latest version

**Comment by MikeRatcliffe** [comment]
Yes, I just noticed that ;o)

I agree that this isn't something that the editor's constructor should be doing ... it should be something that you call yourself, env.editor.focus(). Please log an issue with Fabian for that.

**Comment by nightwing** [comment]
solved in latest ace version
https://github.com/ajaxorg/ace/issues/issue/72/#comment_727931

**Comment by MikeRatcliffe** [comment]
Works in the latest version
